### ISSUE TITLE
Line ending character problem.

### ISSUE THREAD

**Issue by michaelcoll** [Treeptik/CU-infrastructure#1]
Hi,

I had problem with ^M characters in scripts during my install process. (.bashrc, .vimrc, aufs.sh, ...)

I've checkout the project on a Ubuntu distro.

I've found a work around for that problem.

Using this guide : https://help.github.com/articles/dealing-with-line-endings/#platform-linux

 * Executing this command in the repo. `git config core.autocrlf input`
 * Delete all files except the `.git` folder.
 * And executing `git reset HEAD --hard`

This recheckout all files with the correct line ending.

I don't know if it can be corrected on the repo. but it can be cool :)

Thanks.

**Comment by fabienamico** [comment]
Hi @michaelcoll 

In which file the characters appeared ?

Most of time, this comes from Windows system and we all work on Linux System.
In any case we will verify tha we have the good GIT configuration. 

Thanks for your issues

**Comment by michaelcoll** [comment]
My bad.

I need to check that on my computer at home, but it seems to be a bad configuration on my side.

I've checkout the repo. on an other Linux computer and can't reproduce the problem.

Thanks for your help.

**Comment by fabienamico** [comment]
@michaelcoll You're welcome. 
Don't forget to put stars on CloudUnit that will be very :cool:
